service: service-cart

custom:
  #  customDomains:
  #    - http:
  #        stage: dev
  #        domainName: dev-${opt:RANDOM_STRING, '101'}.shopearnpro.com
  #        basePath: ''
  #        apiType: http
  #        endpointType: REGIONAL
  pythonRequirements:
    invalidateCaches: true
    pycache: false
    strip: true
    slim: true
    slimPatterns:
      - '**/__pycache__/**'
      - '**/licenses/**'
      - '**/*.egg-info*'
      - '**/*.exe'
    slimPatternsAppendDefaults: false
  prune:
    automatic: true
    number: 3
  domain: shopearnpro.com
  s3_role_resource: arn:aws:iam::${aws:accountId}:role/s3-access-role
  power_tools_layer: ${file(config.json):AWSLambdaPowerToolsLayerARM}
  db_table: Market_${sls:stage}

provider:
  name: aws
  region: us-east-1
  runtime: python3.13
  architecture: arm64
  logRetentionInDays: 7
  memorySize: 128
  timeout: 8
  iam:
    role:
      statements: ${file(iamroles/default-role.yml)}
  tracing:
    lambda: true
    apiGateway: true
  logs:
    httpApi: true
  httpApi:
    payload: '2.0'
    metrics: true
    disableDefaultEndpoint: false
  environment:
    LOG_LEVEL: INFO
    POWERTOOLS_SERVICE_NAME: service-cart
    POWERTOOLS_METRICS_NAMESPACE: shopnearn
    POWERTOOLS_TRACER_CAPTURE_RESPONSE: true
    POWERTOOLS_TRACER_CAPTURE_ERROR: true
    MARKET_TABLE: ${self:custom.db_table}

functions:
  cart:
    handler: index.handler
    module: lambda/cart
    memorySize: 256
    layers:
      - ${self:custom.power_tools_layer}
      - !Ref DataLambdaLayer
    package:
      patterns:
        - 'lambda/cart/*.*'
    events:
      - httpApi:
          path: /cart/{proxy+}
          method: any
  calc:
    handler: index.handler
    module: lambda/calc
    iamRoleStatementsName: lambda-calc-role
    iamRoleStatements: ${file(iamroles/lambda-calc-role.yml)}
    timeout: 5
    url: true
    layers:
      - ${self:custom.power_tools_layer}
      - !Ref DataLambdaLayer
    package:
      patterns:
        - lambda/calc/*.*
    events:
      - httpApi:
          path: /calc/{proxy+}
          method: any

layers:
  data: # DataLambdaLayer
    path: layer-data
    name: layerData-${sls:stage}
    description: Base lambda layer for ${sls:stage} environment
    package:
      patterns:
        - '**/*.py'
        - '**/*.typed'
        - '**/METADATA'
    compatibleRuntimes:
      - python3.13
    compatibleArchitectures:
      - arm64
    allowedAccounts:
      - '*'
    retain: false

stages:
  default:
    params:
      domain: ${sls:stage}.shopearnpro.com
  prod:
    params:
      domain: shopearnpro.com

resources:
  - Description: shopearnpro application
  - ${file(dbtables/market.yml)}
  - Outputs:
      Domain:
        Description: "shopnearn url link"
        Value: "https://${sls:stage}.${self:custom.domain}"

package:
  individually: true
  exclude:
    - '**'

stepFunctions:
  validate: true
  stateMachines:
    ${file(statemachines/state-machines.yml)}

plugins:
  - serverless-iam-roles-per-function
  - serverless-python-requirements
  # - serverless-domain-manager
  - serverless-step-functions
  - serverless-prune-plugin

app: shopnearn-${sls:stage}
org: sapientum8
