service: shopearn-cart

custom:
  #  customDomains:
  #    - http:
  #        stage: dev
  #        domainName: dev-${opt:RANDOM_STRING, ''}.shopearnpro.com
  #        basePath: ''
  #        apiType: http
  #        endpointType: REGIONAL
  pythonRequirements:
    invalidateCaches: true
    pycache: false
    strip: true
    slim: true
    slimPatterns:
      - '**/__pycache__/**'
      - '**/licenses/**'
      - '**/*.egg-info*'
      - '**/*.exe'
    slimPatternsAppendDefaults: false
  prune:
    automatic: true
    number: 3
  scripts:
    hooks:
      after:deploy:finalize: serverless invoke --function init --aws-profile shopnearn-${sls:stage}
  userPoolClientId:
    Ref: CognitoUserPoolClient
  domain: shopearnpro.com
  s3_role_resource: arn:aws:iam::${aws:accountId}:role/s3-access-role
  power_tools_layer: ${file(config.json):AWSLambdaPowerToolsLayerARM}
  db_table: Market_${sls:stage}

provider:
  name: aws
  region: us-east-1
  runtime: python3.13
  architecture: arm64
  logRetentionInDays: 14
  memorySize: 128
  timeout: 8
  iam:
    role:
      statements: ${file(iamroles/default-role.yml)}
  tracing:
    lambda: true
    apiGateway: true
  logs:
    httpApi: true
  httpApi:
    payload: '2.0'
    metrics: true
    disableDefaultEndpoint: false
    authorizers:
      cognitoAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl:
          Fn::Join:
            - ""
            - - "https://cognito-idp."
              - ${self:provider.region}
              - ".amazonaws.com/"
              - Ref: CognitoUserPool
        audience:
          - ${self:custom.userPoolClientId}
        type: jwt
  environment:
    STAGE: ${opt:stage, 'dev'}
    LOG_LEVEL: INFO
    POWERTOOLS_SERVICE_NAME: service-cart
    POWERTOOLS_METRICS_NAMESPACE: shopnearn
    POWERTOOLS_TRACER_CAPTURE_RESPONSE: true
    POWERTOOLS_TRACER_CAPTURE_ERROR: true
    MARKET_TABLE: ${self:custom.db_table}

functions:
  init:
    handler: init.handler
    module: lambda/scripts
    iamRoleStatementsName: lambda-init-role
    iamRoleStatements: ${file(iamroles/lambda-init-role.yml)}
    timeout: 900
    package:
      patterns:
        - 'lambda/scripts/init.*'
  cart:
    handler: index.handler
    module: lambda/cart
    memorySize: 256
    layers:
      - ${self:custom.power_tools_layer}
      - !Ref DataLambdaLayer
    package:
      patterns:
        - 'lambda/cart/*'
    events:
      - httpApi:
          path: /cart/{proxy+}
          method: any
          authorizer:
            name: cognitoAuthorizer
  calc:
    handler: index.handler
    module: lambda/calc
    iamRoleStatementsName: lambda-calc-role
    iamRoleStatements: ${file(iamroles/lambda-calc-role.yml)}
    ephemeralStorageSize: 512
    timeout: 5
    url: false
    layers:
      - ${self:custom.power_tools_layer}
      - !Ref DataLambdaLayer
    package:
      patterns:
        - 'lambda/calc/*'
    events:
      - httpApi:
          path: /calc/{proxy+}
          method: any

layers:
  data: # DataLambdaLayer
    path: layer-data
    name: layerData-${sls:stage}
    description: Base lambda layer for ${sls:stage} environment
    package:
      patterns:
        - '**/*.py'
        - '**/*.typed'
        - '**/METADATA'
    compatibleRuntimes:
      - python3.13
    compatibleArchitectures:
      - arm64
    allowedAccounts:
      - '*'
    retain: false

stages:
  default:
    params:
      domain: ${sls:stage}.shopearnpro.com
  prod:
    params:
      domain: shopearnpro.com

resources:
  - Description: shopearnpro application
  - Resources: ${file(statemachines/log-group.yml)}
  - Resources: ${file(cognito/userpool.yml)}
  - Resources: ${file(dbtables/market.yml)}
  - Outputs:
      Domain:
        Description: "shopnearn url link"
        Value: "https://${sls:stage}.${self:custom.domain}"

package:
  individually: true
  patterns:
    - '!**'

stepFunctions:
  validate: true
  stateMachines:
    ${file(statemachines/state-machines.yml)}

plugins:
  - serverless-iam-roles-per-function
  - serverless-python-requirements
  # - serverless-domain-manager
  - serverless-step-functions
  - serverless-plugin-scripts
  - serverless-prune-plugin

app: app-${self:service}-${sls:stage}
org: sapientum8
