org: sapientum8
service: service-cart

custom:
  pythonRequirements:
    invalidateCaches: true
    pycache: false
    strip: true
    slim: true
    slimPatterns:
      - '**/__pycache__/**'
      - '**/licenses/**'
      - '**/*.egg-info*'
      - '**/*.exe'
    slimPatternsAppendDefaults: false
  domain: shopearnpro.com
  s3_role_resource: arn:aws:iam::${aws:accountId}:role/s3-access-role
  power_tools_layer: ${file(./config.json):AWSLambdaPowerToolsLayerARM}

provider:
  name: aws
  runtime: python3.13
  architecture: arm64
  memorySize: 128
  timeout: 8
  region: us-east-1
  iam: ${file(iamroles.yml)}
  environment:
    DB_TABLE: Market_${sls:stage}
    LOG_LEVEL: INFO
    VAR1: ${file(./config.${sls:stage}.json):VAR1}

package:
  individually: true
  exclude:
    - '**'

functions:
  cart:
    handler: index.handler
    module: lambda/cart
    memorySize: 256
    layers:
      - !Ref DataLambdaLayer
      - ${self:custom.power_tools_layer}
    package:
      patterns:
        - lambda/cart/*.*
    events:
      - httpApi:
          path: /cart
          method: get
      - httpApi:
          path: /cart/{id}
          method: any
  view:
    handler: index.handler
    module: lambda/view
    url: true
    layers:
      - !Ref DataLambdaLayer
    package:
      patterns:
        - lambda/view/*.*
    events:
      - httpApi:
          path: /view
          method: get
  write:
    handler: index.handler
    module: lambda/write
    timeout: 10
    layers:
      - !Ref DataLambdaLayer
    package:
      patterns:
        - lambda/write/*.*
    events:
      - httpApi:
          path: /write
          method: get

layers:
  data: # DataLambdaLayer
    path: layer-data
    name: layerData-${sls:stage}
    description: DataLambdaLayer for ${sls:stage} environment
    package:
      patterns:
        - '**/*.py'
        - '**/*.typed'
        - '**/METADATA'
    compatibleRuntimes:
      - python3.13
    compatibleArchitectures:
      - arm64
    allowedAccounts:
      - '*'
    retain: false

stages:
  default:
    params:
      domain: ${sls:stage}.shopearnpro.com
  prod:
    params:
      domain: shopearnpro.com

resources:
  - ${file(dbtable.yml)}
  - Outputs:
      Domain:
        Value: "https://${sls:stage}.${self:custom.domain}"

plugins:
  - serverless-python-requirements
