service: shopearn-cart

custom:
  #  customDomains:
  #    - http:
  #        stage: ${sls:stage}
  #        domainName: ${sls:stage}-${sls:instanceId}.${self:custom.domain}
  #        basePath: ''
  #        apiType: http
  #        endpointType: REGIONAL
  pythonRequirements:
    invalidateCaches: true
    pycache: false
    strip: true
    slim: true
    slimPatterns:
      - '**/__pycache__/**'
      - '**/licenses/**'
      - '**/*.egg-info*'
      - '**/*.exe'
    slimPatternsAppendDefaults: false
  prune:
    automatic: true
    number: 3
  scripts:
    hooks:
      after:deploy:finalize: serverless invoke --function init --aws-profile ${param:awsProfile}
  userPoolClientId:
    Ref: CognitoUserPoolClient
  domain: shopearnpro.com
  s3_role_resource: arn:aws:iam::${aws:accountId}:role/s3-access-role
  power_tools_layer: ${file(config.json):AWSLambdaPowerToolsLayerARM}
  db_table: ${param:marketTable}

provider:
  name: aws
  region: us-east-1
  runtime: python3.13
  architecture: arm64
  logRetentionInDays: 14
  memorySize: 128
  timeout: 8
  iam:
    role:
      statements: ${file(iamroles/default-role.yml)}
  tracing:
    lambda: true
    apiGateway: true
  logs:
    httpApi: true
  httpApi:
    payload: '2.0'
    metrics: true
    disableDefaultEndpoint: false
    authorizers:
      cognitoAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl:
          Fn::Join:
            - ""
            - - "https://cognito-idp."
              - ${self:provider.region}
              - ".amazonaws.com/"
              - Ref: CognitoUserPool
        audience:
          - ${self:custom.userPoolClientId}
        type: jwt
  environment:
    LOG_LEVEL: INFO
    STAGE: ${opt:stage,'dev'}
    APP_CONFIG: '${param:config}'
    POWERTOOLS_LOGGER_LOG_EVENT: true
    POWERTOOLS_SERVICE_NAME: shopearn-cart
    POWERTOOLS_METRICS_NAMESPACE: shopnearn
    POWERTOOLS_TRACER_CAPTURE_RESPONSE: true
    POWERTOOLS_TRACER_CAPTURE_ERROR: true
    MARKET_TABLE: ${self:custom.db_table}

functions:
  init:
    handler: init.handler
    module: lambda/scripts
    description: Database init logic
    iamRoleStatementsName: lambda-init-role
    iamRoleStatements: ${file(iamroles/lambda-init-role.yml)}
    timeout: 900
    package:
      patterns:
        - 'lambda/scripts/init.*'
  cart:
    handler: index.handler
    module: lambda/cart
    description: Shopping cart service
    iamRoleStatementsName: lambda-cart-role
    iamRoleStatements: ${file(iamroles/lambda-cart-role.yml)}
    memorySize: 256
    tracing: true
    layers:
      - ${self:custom.power_tools_layer}
      - !Ref AppLambdaLayer
    package:
      patterns:
        - 'lambda/cart/*'
    events:
      - httpApi:
          path: /cart/{proxy+}
          method: any
          authorizer:
            name: cognitoAuthorizer
  calc:
    handler: index.handler
    module: lambda/calc
    description: Bonus calculation logic
    iamRoleStatementsName: lambda-calc-role
    iamRoleStatements: ${file(iamroles/lambda-calc-role.yml)}
    ephemeralStorageSize: 512
    tracing: true
    timeout: 5
    url: false
    layers:
      - ${self:custom.power_tools_layer}
      - !Ref AppLambdaLayer
    package:
      patterns:
        - 'lambda/calc/*'
    events:
      - httpApi:
          path: /calc/{proxy+}
          method: any
  stream:
    handler: market.processor
    module: lambda/stream
    description: Market table stream processor
    iamRoleStatementsName: lambda-ddb-stream-role
    iamRoleStatements: ${file(iamroles/lambda-ddb-stream-role.yml)}
    tracing: true
    layers:
      - ${self:custom.power_tools_layer}
      - !Ref AppLambdaLayer
    package:
      patterns:
        - 'lambda/stream/market.*'
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [ MarketTable, StreamArn ]

layers:
  app: # AppLambdaLayer
    path: app-layer
    name: app-layer-${sls:stage}
    description: Application base lambda layer (${sls:stage})
    package:
      patterns:
        - '**/*.py'
        - '**/*.typed'
        - '**/METADATA'
    compatibleRuntimes:
      - python3.13
    compatibleArchitectures:
      - arm64
    allowedAccounts:
      - '*'
    retain: false

stepFunctions:
  validate: true
  stateMachines:
    ${file(statemachines/state-machines.yml)}

resources:
  - Description: ShopEarnPro Cart Application
  - Resources: ${file(statemachines/log-group.yml)}
  - Resources: ${file(cognito/userpool.yml)}
  - Resources: ${file(dbtables/market.yml)}
  - Outputs:
      Domain:
        Description: "ShopEarnPro URL"
        Value: "https://${param:domain}"

stages:
  default:
    params:
      awsProfile: ${opt:aws-profile,"shopnearn-${opt:stage,'dev'}"}
      domain: ${sls:stage}-${sls:instanceId}-cart.${self:custom.domain}
      config: ${aws:ssm:/${opt:stage,'dev'}/${self:service}/config}
      marketTable: Market_${opt:stage,'dev'}
  prod:
    params:
      awsProfile: ${opt:aws-profile}
      domain: cart.${self:custom.domain}
      config: ${aws:ssm:/prod/${self:service}/config}
      marketTable: Market

package:
  individually: true
  patterns:
    - '!**'

plugins:
  - serverless-iam-roles-per-function
  - serverless-python-requirements
  # - serverless-domain-manager
  - serverless-step-functions
  - serverless-plugin-scripts
  - serverless-prune-plugin

app: app-${self:service}-${sls:stage}
org: sapientum8
